# Generated by Django 5.0.7 on 2024-07-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=100)),
                ('media', models.CharField(choices=[('DVD', 'Dvd'), ('CD', 'Cd'), ('LIVRE', 'Livre')], max_length=10)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('dvd_realisateur', models.CharField(max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_admin.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=100)),
                ('media', models.CharField(choices=[('DVD', 'Dvd'), ('CD', 'Cd'), ('LIVRE', 'Livre')], max_length=10)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('cd_artiste', models.CharField(max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_admin.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jeu_plateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu_name', models.CharField(max_length=100)),
                ('jeu_createur', models.CharField(max_length=100)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('emprunteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_admin.emprunteur')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=100)),
                ('media', models.CharField(choices=[('DVD', 'Dvd'), ('CD', 'Cd'), ('LIVRE', 'Livre')], max_length=10)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('livre_auteur', models.CharField(max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_admin.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
