# Generated by Django 5.0.7 on 2024-07-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_admin.emprunteur'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_admin.emprunteur'),
        ),
        migrations.AlterField(
            model_name='jeu_plateau',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_admin.emprunteur'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediatheque_admin.emprunteur'),
        ),
    ]
